# Generated by Django 5.2.4 on 2025-07-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
